% See also  psinsinit
    pp = [ pp, ...
        rootpath,'\mytest\base;' ...
        rootpath,'\mytest\isimu;' ...
        rootpath,'\mytest\compress;' ...
        rootpath,'\mytest\POS;', ...
        rootpath,'\mytest\POS\base;' ...
        ];
